In [1]:
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

We go back to the data we saved in notebook 05, as it contains the same information as in plotting data and also some str type columns that we could not plot but from which we could extract information during the feature engineering.

In [2]:
df = pd.read_csv('Cleaned Data', index_col = [0])
df.tail(5)

,match_id,year,round,local,visitor,league_id,team1_id_season,team2_id_season,team1_id,team2_id,...,points_visitor,wins_visitor,draws_visitor,losses_visitor,gf_visitor,ga_visitor,avg_visitor,pos_visitor,form_visitor,match_winner
4657,91110,2021,38,Real Oviedo,Sabadell,57314,6382799,6382802,2115,2198,...,40,9.0,13.0,15.0,35,42,-7.0,19,lddww,0
4658,91104,2021,38,FC Cartagena,CD Castellón,57314,6382787,6382788,643,673,...,41,11.0,8.0,18.0,35,43,-8.0,18,wlwdd,0
4659,91112,2021,38,UD Logroñés,Girona,57314,6382792,6391868,1578,1236,...,58,16.0,10.0,11.0,39,34,5.0,6,wlwww,2
4660,91109,2021,38,Rayo Vallecano,Leganés,57314,6382798,6382791,2080,1535,...,62,18.0,8.0,11.0,41,31,10.0,4,wldwd,1
4661,91105,2021,38,Real Sporting,Lugo,57314,6382800,6382793,2125,1598,...,37,8.0,13.0,16.0,32,49,-17.0,21,lllld,0

In [3]:
df.columns

Index(['match_id', 'year', 'round', 'local', 'visitor', 'league_id',
       'team1_id_season', 'team2_id_season', 'team1_id', 'team2_id',
       'local_abbr', 'visitor_abbr', 'division', 'local_goals',
       'visitor_goals', 'result', 'winner', 'points_local', 'wins_local',
       'draws_local', 'losses_local', 'gf_local', 'ga_local', 'avg_local',
       'pos_local', 'form_local', 'points_visitor', 'wins_visitor',
       'draws_visitor', 'losses_visitor', 'gf_visitor', 'ga_visitor',
       'avg_visitor', 'pos_visitor', 'form_visitor', 'match_winner'],
      dtype='object')

#### Results a Round before

In [4]:
def prev1roundlocal(col):
    if col['form_local'][0] == 'w':
        return 3
    if col['form_local'][0] == 'd':
        return 1
    if col['form_local'][0] == 'l':
        return 0

df['round-1_local'] = df.apply(lambda col: prev1roundlocal (col),axis=1)
df['round-1_local']

0       1
1       1
2       3
3       3
4       1
       ..
4657    0
4658    3
4659    3
4660    3
4661    0
Name: round-1_local, Length: 4662, dtype: int64

In [5]:
df['form_local']

0           d
1           d
2           w
3           w
4           d
        ...
4657    ldwld
4658    wddwl
4659    wwdld
4660    wlddl
4661    llldd
Name: form_local, Length: 4662, dtype: object

In [6]:
def prev1roundvisitor(col):
    if col['form_visitor'][1] == 'w':
        return 3
    if col['form_visitor'][1] == 'd':
        return 1
    if col['form_visitor'][1] == 'l':
        return 0

df['round-1_visitor'] = df.apply(lambda col: prev1roundlocal (col),axis=1)
df['round-1_visitor'].tail()

4657    0
4658    3
4659    3
4660    3
4661    0
Name: round-1_visitor, dtype: int64

In [7]:
df.head(5)

,match_id,year,round,local,visitor,league_id,team1_id_season,team2_id_season,team1_id,team2_id,...,draws_visitor,losses_visitor,gf_visitor,ga_visitor,avg_visitor,pos_visitor,form_visitor,match_winner,round-1_local,round-1_visitor
0,37467,2016,2,Villarreal,Espanyol,15373,214625,214629,2716,998,...,0.0,0.0,1,0,1.0,5,w,0,1,1
1,37471,2016,2,R. Sociedad,Real Sporting,15373,214631,214619,2120,2125,...,1.0,0.0,0,0,0.0,13,d,1,1,1
2,37463,2016,2,Barcelona,Málaga,15373,214620,214628,429,1617,...,1.0,0.0,0,0,0.0,9,d,0,3,3
3,37457,2016,2,Celta,Rayo Vallecano,15373,214627,214630,712,2080,...,1.0,0.0,0,0,0.0,11,d,0,3,3
4,37469,2016,2,Real Madrid,Real Betis,15373,214621,214618,2107,486,...,1.0,0.0,1,1,0.0,6,d,0,1,1

In order to extract information of previous rounds from columns 'form_local' & 'form_visitor' is necessary to put into the same length the strings from each row in this colums. We will fill the spaces with 'n' from none.

In [8]:
max_length = df.form_local.map(len).max()
df.form_local = df.form_local.apply(lambda x: x + 'n'*(max_length - len(x)))
df['form_local']

0       dnnnn
1       dnnnn
2       wnnnn
3       wnnnn
4       dnnnn
        ...
4657    ldwld
4658    wddwl
4659    wwdld
4660    wlddl
4661    llldd
Name: form_local, Length: 4662, dtype: object

In [9]:
df.form_visitor = df.form_visitor.apply(lambda x: x + 'n'*(max_length - len(x)))
df['form_visitor']

0       wnnnn
1       dnnnn
2       dnnnn
3       dnnnn
4       dnnnn
        ...
4657    lddww
4658    wlwdd
4659    wlwww
4660    wldwd
4661    lllld
Name: form_visitor, Length: 4662, dtype: object

We create new columns assigning points to the home and away teams according to their results in the last matches. In order not to confuse the model, when we do not have information about the result of the round in question (this happens in the first rounds), we will assign an indicative value to the coefficient, different from 0, 1 and 3, so as not to confuse the lack of information with wins, draws or defeats.

#### Results 2 Rounds before

In [10]:
def prev2roundlocal(col):
    if col['form_local'][1] == 'n':
        return 1.5
    if col['form_local'][1] == 'w':
        return 3
    if col['form_local'][1] == 'd':
        return 1
    if col['form_local'][1] == 'l':
        return 0

df['round-2_local'] = df.apply(lambda col: prev2roundlocal (col),axis=1)
df['round-2_local'].head()

0    1.5
1    1.5
2    1.5
3    1.5
4    1.5
Name: round-2_local, dtype: float64

In [11]:
def prev2roundvisitor(col):
    if col['form_visitor'][1] == 'n':
        return 1.5
    if col['form_visitor'][1] == 'w':
        return 3
    if col['form_visitor'][1] == 'd':
        return 1
    if col['form_visitor'][1] == 'l':
        return 0

df['round-2_visitor'] = df.apply(lambda col: prev2roundvisitor (col),axis=1)
df['round-2_visitor'].tail()

4657    1.0
4658    0.0
4659    0.0
4660    0.0
4661    0.0
Name: round-2_visitor, dtype: float64

#### Results 3 Rounds before

In [12]:
def prev3roundlocal(col):
    if col['form_local'][2] == 'n':
        return 1.5
    if col['form_local'][2] == 'w':
        return 3
    if col['form_local'][2] == 'd':
        return 1
    if col['form_local'][2] == 'l':
        return 0

df['round-3_local'] = df.apply(lambda col: prev3roundlocal (col),axis=1)
df['round-3_local'].head()

0    1.5
1    1.5
2    1.5
3    1.5
4    1.5
Name: round-3_local, dtype: float64

In [13]:
def prev3roundvisitor(col):
    if col['form_visitor'][2] == 'n':
        return 1.5
    if col['form_visitor'][2] == 'w':
        return 3
    if col['form_visitor'][2] == 'd':
        return 1
    if col['form_visitor'][2] == 'l':
        return 0

df['round-3_visitor'] = df.apply(lambda col: prev3roundvisitor (col),axis=1)
df['round-3_visitor'].tail()

4657    1.0
4658    3.0
4659    3.0
4660    1.0
4661    0.0
Name: round-3_visitor, dtype: float64

#### Results 4 Rounds before

In [14]:
def prev4roundlocal(col):
    if col['form_local'][3] == 'n':
        return 1.5
    if col['form_local'][3] == 'w':
        return 3
    if col['form_local'][3] == 'd':
        return 1
    if col['form_local'][3] == 'l':
        return 0

df['round-4_local'] = df.apply(lambda col: prev4roundlocal (col),axis=1)
df['round-4_local'].head()

0    1.5
1    1.5
2    1.5
3    1.5
4    1.5
Name: round-4_local, dtype: float64

In [15]:
def prev4roundvisitor(col):
    if col['form_visitor'][1] == 'n':
        return 1.5
    if col['form_visitor'][1] == 'w':
        return 3
    if col['form_visitor'][1] == 'd':
        return 1
    if col['form_visitor'][1] == 'l':
        return 0

df['round-4_visitor'] = df.apply(lambda col: prev4roundvisitor (col),axis=1)
df['round-4_visitor'].tail()

4657    1.0
4658    0.0
4659    0.0
4660    0.0
4661    0.0
Name: round-4_visitor, dtype: float64

##### Results 5 Rounds before

In [16]:
def prev5roundlocal(col):
    if col['form_local'][4] == 'n':
        return 1.5
    if col['form_local'][4] == 'w':
        return 3
    if col['form_local'][4] == 'd':
        return 1
    if col['form_local'][4] == 'l':
        return 0

df['round-5_local'] = df.apply(lambda col: prev5roundlocal (col),axis=1)
df['round-5_local'].head()

0    1.5
1    1.5
2    1.5
3    1.5
4    1.5
Name: round-5_local, dtype: float64

In [17]:
def prev5roundvisitor(col):
    if col['form_visitor'][4] == 'n':
        return 1.5
    if col['form_visitor'][4] == 'w':
        return 3
    if col['form_visitor'][4] == 'd':
        return 1
    if col['form_visitor'][4] == 'l':
        return 0

df['round-5_visitor'] = df.apply(lambda col: prev5roundvisitor (col),axis=1)
df['round-5_visitor'].tail()

4657    3.0
4658    1.0
4659    3.0
4660    1.0
4661    1.0
Name: round-5_visitor, dtype: float64

In [18]:
df.head(5)

,match_id,year,round,local,visitor,league_id,team1_id_season,team2_id_season,team1_id,team2_id,...,round-1_local,round-1_visitor,round-2_local,round-2_visitor,round-3_local,round-3_visitor,round-4_local,round-4_visitor,round-5_local,round-5_visitor
0,37467,2016,2,Villarreal,Espanyol,15373,214625,214629,2716,998,...,1,1,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5
1,37471,2016,2,R. Sociedad,Real Sporting,15373,214631,214619,2120,2125,...,1,1,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5
2,37463,2016,2,Barcelona,Málaga,15373,214620,214628,429,1617,...,3,3,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5
3,37457,2016,2,Celta,Rayo Vallecano,15373,214627,214630,712,2080,...,3,3,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5
4,37469,2016,2,Real Madrid,Real Betis,15373,214621,214618,2107,486,...,1,1,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5

#### Coefficients of points accumulated in the last rounds

Creating new columns with the points accumulated int he last rounds from each team.

In [19]:
col_local_list = list (df)
col_local_list.remove('match_id',
 'year',
 'round',
 'local',
 'visitor',
 'league_id',
 'team1_id_season',
 'team2_id_season',
 'team1_id',
 'team2_id',
 'local_abbr',
 'visitor_abbr',
 'division',
 'local_goals',
 'visitor_goals',
 'result',
 'winner',
 'points_local',
 'wins_local',
 'draws_local',
 'losses_local',
 'gf_local',
 'ga_local',
 'avg_local',
 'pos_local',
 'form_local',
 'points_visitor',
 'wins_visitor',
 'draws_visitor',
 'losses_visitor',
 'gf_visitor',
 'ga_visitor',
 'avg_visitor',
 'pos_visitor',
 'form_visitor',
 'match_winner',
 'round-1_local',
 'round-1_visitor',
 'round-2_local',
 'round-3_local',
 'round-3_visitor',
 'round-4_local',
 'round-4_visitor',
 'round-5_local',
 'round-5_visitor')

TypeError: remove() takes exactly one argument (45 given)

In [ ]:
df['pts_last3_local'] = df.apply(lambda x: x['round-1_local'] + x['round-2_local'] + x['round-3_local'], axis=1)
df['pts_last3_local'].head()

In [20]:
print(df['round-1_local'], df['round-2_local'], df['round-3_local'])

0       1
1       1
2       3
3       3
4       1
       ..
4657    0
4658    3
4659    3
4660    3
4661    0
Name: round-1_local, Length: 4662, dtype: int64 0       1.5
1       1.5
2       1.5
3       1.5
4       1.5
       ...
4657    1.0
4658    1.0
4659    3.0
4660    0.0
4661    0.0
Name: round-2_local, Length: 4662, dtype: float64 0       1.5
1       1.5
2       1.5
3       1.5
4       1.5
       ...
4657    3.0
4658    1.0
4659    1.0
4660    1.0
4661    0.0
Name: round-3_local, Length: 4662, dtype: float64

In [21]:
df['pts_last2_local'] = df.apply(lambda x: x['round-1_local'] + x['round-2_local'] , axis=1)
df['pts_last4_local'] = df.apply(lambda x: x['round-1_local'] + x['round-2_local'] + x['round-3_local'] + x['round-4_local'] , axis=1)
df['pts_last5_local'] = df.apply(lambda x: x['round-1_local'] + x['round-2_local'] + x['round-3_local'] + x['round-4_local'] + x['round-5_local'], axis=1)
df['pts_last2_visitor'] = df.apply(lambda x: x['round-1_visitor'] + x['round-2_visitor'] , axis=1)
df['pts_last3_visitor'] = df.apply(lambda x: x['round-1_visitor'] + x['round-2_visitor'] + x['round-3_visitor']  , axis=1)
df['pts_last4_visitor'] = df.apply(lambda x: x['round-1_visitor'] + x['round-2_visitor'] + x['round-3_visitor'] + x['round-4_visitor'] , axis=1)
df['pts_last5_visitor'] = df.apply(lambda x: x['round-1_visitor'] + x['round-2_visitor'] + x['round-3_visitor'] + x['round-4_visitor'] + x['round-5_visitor'], axis=1)

In [23]:
df.tail(10)

,match_id,year,round,local,visitor,league_id,team1_id_season,team2_id_season,team1_id,team2_id,...,round-4_visitor,round-5_local,round-5_visitor,pts_last2_local,pts_last4_local,pts_last5_local,pts_last2_visitor,pts_last3_visitor,pts_last4_visitor,pts_last5_visitor
4652,91108,2021,38,Ponferradina,Albacete,57314,6382797,6382785,3287,140,...,0.0,0.0,0.0,1.0,5.0,5.0,0.0,3.0,3.0,3.0
4653,91113,2021,38,Real Zaragoza,Espanyol,57314,6390092,6382789,2136,998,...,3.0,1.0,3.0,6.0,7.0,8.0,6.0,7.0,10.0,13.0
4654,91103,2021,38,Alcorcón,Las Palmas,57314,6382786,6382790,64,2563,...,1.0,3.0,3.0,3.0,6.0,9.0,1.0,2.0,3.0,6.0
4655,91106,2021,38,Málaga,Mallorca,57314,6382794,6382795,1617,1623,...,3.0,0.0,3.0,6.0,7.0,7.0,6.0,6.0,9.0,12.0
4656,91107,2021,38,Mirandés,Fuenlabrada,57314,6382796,6387869,1699,1179,...,1.0,0.0,3.0,3.0,5.0,5.0,4.0,5.0,6.0,9.0
4657,91110,2021,38,Real Oviedo,Sabadell,57314,6382799,6382802,2115,2198,...,1.0,1.0,3.0,1.0,4.0,5.0,1.0,2.0,3.0,6.0
4658,91104,2021,38,FC Cartagena,CD Castellón,57314,6382787,6382788,643,673,...,0.0,0.0,1.0,4.0,8.0,8.0,3.0,6.0,6.0,7.0
4659,91112,2021,38,UD Logroñés,Girona,57314,6382792,6391868,1578,1236,...,0.0,1.0,3.0,6.0,7.0,8.0,3.0,6.0,6.0,9.0
4660,91109,2021,38,Rayo Vallecano,Leganés,57314,6382798,6382791,2080,1535,...,0.0,0.0,1.0,3.0,5.0,5.0,3.0,4.0,4.0,5.0
4661,91105,2021,38,Real Sporting,Lugo,57314,6382800,6382793,2125,1598,...,0.0,1.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0

#### Diferencia de puntos y de avg

In [24]:
df['pts_difference'] = df.apply(lambda x: x['points_local'] - x['points_visitor'] , axis=1)
df['avg_difference'] = df.apply(lambda x: x['avg_local'] - x['avg_visitor'] , axis=1)

In [25]:
df.head(5)

,match_id,year,round,local,visitor,league_id,team1_id_season,team2_id_season,team1_id,team2_id,...,round-5_visitor,pts_last2_local,pts_last4_local,pts_last5_local,pts_last2_visitor,pts_last3_visitor,pts_last4_visitor,pts_last5_visitor,pts_difference,avg_difference
0,37467,2016,2,Villarreal,Espanyol,15373,214625,214629,2716,998,...,1.5,2.5,5.5,7.0,2.5,4.0,5.5,7.0,-2,-1.0
1,37471,2016,2,R. Sociedad,Real Sporting,15373,214631,214619,2120,2125,...,1.5,2.5,5.5,7.0,2.5,4.0,5.5,7.0,0,0.0
2,37463,2016,2,Barcelona,Málaga,15373,214620,214628,429,1617,...,1.5,4.5,7.5,9.0,4.5,6.0,7.5,9.0,2,1.0
3,37457,2016,2,Celta,Rayo Vallecano,15373,214627,214630,712,2080,...,1.5,4.5,7.5,9.0,4.5,6.0,7.5,9.0,2,1.0
4,37469,2016,2,Real Madrid,Real Betis,15373,214621,214618,2107,486,...,1.5,2.5,5.5,7.0,2.5,4.0,5.5,7.0,0,0.0

### Duda Pablo

Como meter una variable categorica como input (id equipos: team1_id_season y team1_id)

In [18]:
df['round-2_local'] = df['form_local'].apply(lambda x: x[1])
df['round-3__local'] = df['form_local'].apply(lambda x: x[2])
df['round-4__local'] = df['form_local'].apply(lambda x: x[3])
df['round-5__local'] = df['form_local'].apply(lambda x: x[4])
df['round-1_visitor'] = df['form_visitor'].apply(lambda x: x[0])
df['round-2_visitor'] = df['form_visitor'].apply(lambda x: x[1])
df['round-3_visitor'] = df['form_visitor'].apply(lambda x: x[2])
df['round-4_visitor'] = df['form_visitor'].apply(lambda x: x[3])
df['round-5_visitor'] = df['form_visitor'].apply(lambda x: x[4])

IndexError: string index out of range

In [ ]:
df['score_local'] = df['result'].apply(lambda x: x.split("-")[0])
df['score_visitor'] = df['result'].apply(lambda x: x.split("-")[1])