# Introducing data

In [1]:
import pandas as pd 
import numpy as np 
import os 
import requests
import json

#### At first, we request all necessary data, that is, every match result from La Liga Santander & La Liga Smartbank in the last 5 years. This request is done through BeSoccer API.

In [2]:
#Todas las jornadas (38) primera division y segunda division españolas 2018-2021
for league_division in range(1, 3):
    for league_season in range(2018, 2022):
        for league_round in range(1, 39):
            matches_url = f"https://apiclient.besoccerapps.com/scripts/api/api.php?key=023afbc77c5610fefc3fc8976e451752&tz=Europe/Madrid&format=json&req=matchs&league={league_division}&round={league_round}&order=twin&twolegged=1&year={league_season}"
            response = requests.get(matches_url)
            result = json.loads(response.content)
            if league_round == 1 and league_division == 1 and league_season == 2018:
                df1 = pd.DataFrame(result['match'])
            else:
                df1 = df1.append(result['match'])

In [3]:
df1

,id,year,group,total_group,round,local,visitor,league_id,stadium,team1,...,visitor_goals,result,live_minute,status,channels,winner,penaltis1,penaltis2,prorroga,stadium2
0,494771,2018,1,1,1,Leganés,Alavés,38645,Municipal de Butarque,783064,...,0,1-0,,1,"[{'id': '185', 'name': 'beIN LaLiga', 'image':...",783064,0,0,False,NaN
1,494768,2018,1,1,1,Valencia,Las Palmas,38645,Mestalla,783071,...,0,1-0,,1,"[{'id': '185', 'name': 'beIN LaLiga', 'image':...",783071,0,0,False,NaN
2,494767,2018,1,1,1,Celta,R. Sociedad,38645,Abanca Balaídos,783059,...,3,2-3,,1,"[{'id': '185', 'name': 'beIN LaLiga', 'image':...",783067,0,0,False,NaN
3,494773,2018,1,1,1,Girona,Atlético,38645,Montilivi,784236,...,2,2-2,,1,"[{'id': '185', 'name': 'beIN LaLiga', 'image':...",0,0,0,False,NaN
4,494765,2018,1,1,1,Sevilla,Espanyol,38645,Ramón Sánchez Pizjuán,783070,...,1,1-1,,1,"[{'id': '185', 'name': 'beIN LaLiga', 'image':...",0,0,0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,91110,2021,1,1,38,Real Oviedo,Sabadell,57314,Carlos Tartiere,6382799,...,1,2-1,,1,"[{'id': '325', 'name': 'M. LaLiga', 'image': '...",6382799,0,0,False,NaN
7,91104,2021,1,1,38,FC Cartagena,CD Castellón,57314,Municipal Cartagonova,6382787,...,0,1-0,,1,"[{'id': '325', 'name': 'M. LaLiga', 'image': '...",6382787,0,0,False,NaN
8,91112,2021,1,1,38,UD Logroñés,Girona,57314,Las Gaunas,6382792,...,4,1-4,,1,"[{'id': '325', 'name': 'M. LaLiga', 'image': '...",6391868,0,0,False,NaN
9,91109,2021,1,1,38,Rayo Vallecano,Leganés,57314,Vallecas,6382798,...,1,1-1,,1,"[{'id': '303', 'name': '#Vamos', 'image': 'htt...",0,0,0,False,NaN
10,91105,2021,1,1,38,Real Sporting,Lugo,57314,El Molinón-Enrique Castro Quini,6382800,...,0,1-0,,1,"[{'id': '325', 'name': 'M. LaLiga', 'image': '...",6382800,0,0,False,NaN

#### We add for La Liga Smartbank four more rounds, as this division has two more teams

In [4]:
for league_season in range(2018, 2022):
    for league_round in range(39, 43):
        smartbank_extraround_url = f"https://apiclient.besoccerapps.com/scripts/api/api.php?key=023afbc77c5610fefc3fc8976e451752&tz=Europe/Madrid&format=json&req=matchs&league=2&round={league_round}&order=twin&twolegged=1&year={league_season}"
        response_extra = requests.get(smartbank_extraround_url)
        result_extra = json.loads(response_extra.content)
        df1 = df1.append(result['match'])

In [5]:
df1.columns

Index(['id', 'year', 'group', 'total_group', 'round', 'local', 'visitor',
       'league_id', 'stadium', 'team1', 'team2', 'conference', 'dteam1',
       'dteam2', 'numc', 'no_hour', 'local_abbr', 'visitor_abbr', 'isVideo',
       'numVideos', 'competition_name', 'competition_id', 'split_league',
       'type', 'type_id', 'playoffs', 'group_code', 'total_rounds', 'coef',
       'cflag_local', 'cflag_visitor', 'local_shield', 'visitor_shield',
       'extraTxt', 'schedule', 'date', 'hour', 'minute', 'local_goals',
       'visitor_goals', 'result', 'live_minute', 'status', 'channels',
       'winner', 'penaltis1', 'penaltis2', 'prorroga', 'stadium2'],
      dtype='object')

#### We drop out the columns that we evidently don´t need, and after that we research the content of other that are suspicious of being also dropped.

In [6]:
df2 = df1.drop(['stadium', 'group', 'total_group', 'no_hour', 'status', 'isVideo', 'playoffs', 'penaltis1', 'penaltis2', 'prorroga', 'stadium2', 'channels','hour','minute', 'extraTxt', 'cflag_local', 'cflag_visitor','conference','local_shield', 'visitor_shield', 'schedule', 'total_rounds', 'type_id', 'type', 'split_league', 'live_minute', 'numVideos', 'no_hour', 'numc'] , axis = 1 )

In [7]:
df2

,id,year,round,local,visitor,league_id,team1,team2,dteam1,dteam2,...,visitor_abbr,competition_name,competition_id,group_code,coef,date,local_goals,visitor_goals,result,winner
0,494771,2018,1,Leganés,Alavés,38645,783064,783055,1535,137,...,ALA,Primera División,1,1,76.000,2017/08/18,1,0,1-0,783064
1,494768,2018,1,Valencia,Las Palmas,38645,783071,783063,2647,2563,...,UDL,Primera División,1,1,76.000,2017/08/18,1,0,1-0,783071
2,494767,2018,1,Celta,R. Sociedad,38645,783059,783067,712,2120,...,RSO,Primera División,1,1,76.000,2017/08/19,2,3,2-3,783067
3,494773,2018,1,Girona,Atlético,38645,784236,783057,1236,369,...,ATM,Primera División,1,1,76.000,2017/08/19,2,2,2-2,0
4,494765,2018,1,Sevilla,Espanyol,38645,783070,783062,1102,998,...,ESP,Primera División,1,1,76.000,2017/08/19,1,1,1-1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6,91110,2021,38,Real Oviedo,Sabadell,57314,6382799,6382802,2115,2198,...,SAB,Segunda División,2,1,58.462,2021/05/09,2,1,2-1,6382799
7,91104,2021,38,FC Cartagena,CD Castellón,57314,6382787,6382788,643,673,...,CAS,Segunda División,2,1,58.462,2021/05/09,1,0,1-0,6382787
8,91112,2021,38,UD Logroñés,Girona,57314,6382792,6391868,1578,1236,...,GIR,Segunda División,2,1,58.462,2021/05/09,1,4,1-4,6391868
9,91109,2021,38,Rayo Vallecano,Leganés,57314,6382798,6382791,2080,1535,...,LEG,Segunda División,2,1,58.462,2021/05/10,1,1,1-1,0
10,91105,2021,38,Real Sporting,Lugo,57314,6382800,6382793,2125,1598,...,LUG,Segunda División,2,1,58.462,2021/05/10,1,0,1-0,6382800

In [8]:
dteam_meaning = df2['dteam1'] == '1535'
dteam_meaning.head()

0     True
1    False
2    False
3    False
4    False
Name: dteam1, dtype: bool

In [9]:
dteam_1535 = df2[dteam_meaning]
dteam_1535.tail()

,id,year,round,local,visitor,league_id,team1,team2,dteam1,dteam2,...,visitor_abbr,competition_name,competition_id,group_code,coef,date,local_goals,visitor_goals,result,winner
2,90646,2021,28,Leganés,CD Castellón,57314,6382791,6382788,1535,673,...,CAS,Segunda División,2,1,58.462,2021/03/06,0,0,0-0,0
3,90667,2021,30,Leganés,Fuenlabrada,57314,6382791,6387869,1535,1179,...,FUE,Segunda División,2,1,58.462,2021/03/20,0,2,0-2,6387869
6,91056,2021,33,Leganés,Sabadell,57314,6382791,6382802,1535,2198,...,SAB,Segunda División,2,1,58.462,2021/04/04,2,1,2-1,6382791
9,91078,2021,35,Leganés,Ponferradina,57314,6382791,6382797,1535,3287,...,PON,Segunda División,2,1,58.462,2021/04/19,1,1,1-1,0
6,91099,2021,37,Leganés,Real Sporting,57314,6382791,6382800,1535,2125,...,SPO,Segunda División,2,1,58.462,2021/05/02,0,0,0-0,0

#### We realise that 'dteam' columns are identifyers for teams, but also 'team1' and 'team 2'. Researching into API documentation we find out the difference.  'team' is an identifyer of the team only for that season and  'dteam' is the unique team identifyer for all the seasons and competitions. For the moment we remain these columns. 
#### For any other user doubts, here the documentation with columns meanings: https://company.besoccer.com/api/documentacion/matchs